# Generated by Django 4.1.8 on 2023-04-13 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('handle', models.SlugField(unique=True)),
                ('sku', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, max_length=10)),
                ('description', models.TextField()),
                ('on_sale', models.BooleanField(default=False)),
                ('sale_percentage', models.IntegerField(default=5)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, max_length=10)),
                ('sale_created_at', models.DateTimeField(auto_now_add=True)),
                ('sale_starts_at', models.DateTimeField(blank=True, null=True)),
                ('sale_ends_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.CharField(choices=[('n', 'None'), ('l', 'Law'), ('s', 'Sexual'), ('f', 'Forgery'), ('m', 'Man-in-the-middle'), ('r', 'Replicate'), ('c', 'Custom')], default=('n', 'None'), max_length=20)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
